### ISSUE TITLE
Update plugin to use more recent dnsmasq

### ISSUE THREAD

**Issue by sthamel** [OpenMediaVault-Plugin-Developers/openmediavault-dnsmasq#3]
The plugin uses version 2.62 and 2.73 has been released.  There are occasions the dnsmasq processes uses heavy cpu.

In my case (omv 2.0), the cpu hovers around 16%.  There are other incidents reported with 100%.  Some of the runaway process issues have been resolved in the newer dnsmasqs.

I love the plugin and have used it for > 1 year....  I'm not familiar with omv plugin development, but would try to help anyway I can.  Thanks in advance.

**Comment by subzero79** [comment]
Mostly all packages in OMV are provided by Debian repositories of wheezy, including dnsmasq. In this case the Jessie or testing version is not compatible, since it requires libc6 higher than 2.15. 

You can try to build you're own package of dnsmasq if you want. Changing the libc6 to higher version is a no go at the moment.

**Comment by ryecoaaron** [comment]
I tried to build 2.72 from Jessie and 2.73 from Stretch with no luck.  So, this will have to wait for OMV 3.x which will be based on Jessie.
